### PR TITLE
pluralize entity and update dependencies

### LINKED ISSUE #25: NPM Package too old, it seems not work with latest version of gatsby and strapi
Can this be updated??

### PR DESCRIPTION
**Pull request by aDEVE**
- Update dependencies. 
- Pluralize endpoint.

Fix #25 #22

### CODE REVIEW

File: src/fetch.js [hunk 1]
```diff
@@ -1,12 +1,13 @@
...
+import pluralize from 'pluralize'
 
 module.exports = async ({ apiURL, contentType, jwtToken }) => {
   console.time('Fetch Strapi data')
-  console.log(`Starting to fetch data from Strapi (${contentType})`)
+  console.log(`Starting to fetch data from Strapi (${pluralize(contentType)})`)
 
   // Define API endpoint.
-  const apiEndpoint = `${apiURL}/${contentType}`
+  const apiEndpoint = `${apiURL}/${pluralize(contentType)}`
```
Comment (gonzochic) [inline src/fetch.js]: @aDEVE your changes lead to an error on my side.  More concretely this line in  causes a `404` Error during the `gatsby develop` step.

I am using Strapi 3.0.0-alpha.14 and my endpoints are not pluralized 

e.g. the endpoint is `/product` but the pluralization changes it in `/products`. Could you give me some insights why you added the pluralization. I am pretty sure you had a good reason to do so (and it seems to work for you)

**Comment by gonzochic** [comment]
ok, now i understand https://github.com/strapi/strapi/pull/1725

TBH it is pretty hardcore from Strapi to pluralize the API under the same API-Version. Pretty much breaking the rest of the ecosystem (e.g. my provisioning scripts, etc).
